name: Compile Kernel

on:
  workflow_dispatch:
    inputs:
      clang_version:
        description: 选择您内核对应的clang
        required: true
        type: choice
        default: clang-r563880c
        options:
          - clang-3289846
          - clang-r547379
          - clang-r563880
          - clang-r563880c
          - clang-r574158
          - clang-r487747c
          - clang-stable
          
      kernel_source:
        description: 内核源码
        required: true
        type: choice
        default: LineageOS
        options:
          - LineageOS
          - crdroidandroid
          
      kernel_branch:
        description: "内核分支(就像: lineage-23.2 sixteen-qpr1)"
        required: true
        type: string
        default: "lineage-23.2"
        
      ksu_type:
        description: "KernelSU Version"
        required: true
        type: choice
        default: ReSukiSU-with-susfs-BBG-KPM
        options:
          - None
          - Official-KernelSU
          - KernelSU-Next
          - KernelSU-Next-with-susfs
          - KowSU
          - ReSukiSU
          - ReSukiSU-with-susfs
          - ReSukiSU-with-susfs-BBG-KPM
          
jobs:
  Kernel_CI:
    env:
        GH_TOKEN: ${{ github.token }}
        SOC: sm8650
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
          
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu \
          gawk
          
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/android_kernel_oneplus_${SOC}.git ${SOC}
          git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/android_kernel_oneplus_${SOC}-modules.git ${SOC}-modules

      - name: Download AOSP Clang
        run: |
          mkdir -p toolchains/${{ inputs.clang_version }}
          cd toolchains

          curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/${{ inputs.clang_version }}.tar.gz
          tar -xf "${{ inputs.clang_version }}.tar.gz" -C ${{ inputs.clang_version }}

      - name: Compile Kernel
        run: |
          CLANG_ROOT="${GITHUB_WORKSPACE}/toolchains/${{ inputs.clang_version }}/bin"
          export PATH="${CLANG_ROOT}:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CC="${CLANG_ROOT}/clang"
          export CXX="${CLANG_ROOT}/clang++"
          export HOSTCC="${CLANG_ROOT}/clang"
          export HOSTCXX="${CLANG_ROOT}/clang++"
          export LD="${CLANG_ROOT}/ld.lld"
          export AR="${CLANG_ROOT}/llvm-ar"
          export NM="${CLANG_ROOT}/llvm-nm"
          export OBJCOPY="${CLANG_ROOT}/llvm-objcopy"
          export OBJDUMP="${CLANG_ROOT}/llvm-objdump"
          export STRIP="${CLANG_ROOT}/llvm-strip"

          cd ${SOC}

          case "${{ inputs.ksu_type }}" in
          
            "None")
              ;;
              
            "Official-KernelSU")
              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
              ;;
              
            "KowSU")
               curl -LSs "https://raw.githubusercontent.com/KOWX712/KernelSU/main/kernel/setup.sh" | bash -s master
              ;;

            "KernelSU-Next")
              curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
              ;;

            "KernelSU-Next-with-susfs")
              curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
              ;;

            "ReSukiSU"|"ReSukiSU-with-susfs"|"ReSukiSU-with-susfs-BBG-KPM")
              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main
              ;;
          esac
          
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig
          
          if [[ "${{ inputs.ksu_type }}" == *susfs* ]]; then
            git clone -b gki-android14-6.1 https://gitlab.com/simonpunk/susfs4ksu.git susfs
            cd susfs
            cp ./kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ..
            cp ./kernel_patches/fs/* ../fs/
            cp ./kernel_patches/include/linux/* ../include/linux/
            cd ..
            patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
            echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> arch/arm64/configs/gki_defconfig
          fi

          if [[ "${{ inputs.ksu_type }}" == *BBG* ]]; then
            wget -O- https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
            sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' security/Kconfig
          fi
          
          touch ./.scmversion
          
          if [[ "${{ inputs.ksu_type }}" == *KPM* ]]; then
            echo "CONFIG_KPM=y" >> arch/arm64/configs/gki_defconfig
          fi
          
          echo "CONFIG_TMPFS_XATTR=y" >> arch/arm64/configs/gki_defconfig

          rm android/abi_gki_protected_exports_*
          
          make O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config vendor/debugfs.config
          
          make -j2 O=out Image
          
          if [[ "${{ inputs.ksu_type }}" == *KPM* ]]; then
            cd ${SOC}/out/arch/arm64/boot/
            wget https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.13.0/patch_linux
            chmod +x patch_linux
            ./patch_linux
            rm -f Image
            mv oImage Image
          fi

      - name: Make AnyKernel3
        run: |
          ZIP_NAME="${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          git clone https://github.com/Kernel-SU/AnyKernel3.git

          cp ${SOC}/out/arch/arm64/boot/Image AnyKernel3/Image
          cp ${SOC}/out/arch/arm64/boot/Image ./Image
          cd AnyKernel3

          zip -r9 ../"${ZIP_NAME}.zip" * -x .git

      - name: Create GitHub Release
        run: |
          REL_NAME="${SOC}_${{ inputs.kernel_source }}-${{ inputs.kernel_branch }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          cd ${GITHUB_WORKSPACE}
          ZIP_FILE=$(ls *.zip)
          gh release create "$REL_NAME" --title "$REL_NAME" --notes "" "${ZIP_FILE}" Image
